from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .auth_views import (
    AnonymousSessionView,
    CsrfTokenView,
    DeleteAccountView,
    DeleteDataView,
    DemoUsersView,
    ExportConversationsView,
    ExportMemoryGraphView,
    LoginView,
    LogoutView,
    PromoteAnonymousView,
    SessionView,
    SignupView,
)
from .journey_views import (
    JourneyProfileView,
    JourneyStateView,
    ProvocationResponseView,
    SoulProfileView,
    ValueProfileView,
)
from .views import (
    AnalysisAskView,
    AnalysisView,
    AskView,
    AudioBatchTranscribeView,
    RealtimeTokenView,
    EventDetailView,
    EventListCreateView,
    PatternDetailView,
    PatternListView,
    PatternRecomputeView,
    CharacterProfileListCreateView,
    CharacterProfileDetailView,
    CharacterProfileAnalyzeView,
    ReflectionStartView,
    ReflectionNextView,
    ScreenplayAnalyzeView,
    ScreenplayParseView,
    ScreenplayDatasetListView,
    ScreenplayDatasetDetailView,
    CharacterNetworkBuildView,
    ConversationImportView,
    GraphTestsView,
    GraphQueryView,
    LiveConversationView,
)

urlpatterns = [
    path("auth/csrf/", CsrfTokenView.as_view(), name="auth-csrf"),
    path("auth/me/", SessionView.as_view(), name="auth-session"),
    path("auth/signup/", SignupView.as_view(), name="auth-signup"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/anonymous/", AnonymousSessionView.as_view(), name="auth-anonymous"),
    path("auth/promote/", PromoteAnonymousView.as_view(), name="auth-promote"),
    path("auth/demo-users/", DemoUsersView.as_view(), name="auth-demo-users"),
    path("auth/data/", DeleteDataView.as_view(), name="auth-delete-data"),
    path("auth/account/", DeleteAccountView.as_view(), name="auth-delete-account"),
    path("auth/export/conversations/", ExportConversationsView.as_view(), name="auth-export-conversations"),
    path("auth/export/memory-graph/", ExportMemoryGraphView.as_view(), name="auth-export-memory-graph"),
    path("events/", EventListCreateView.as_view(), name="events-list-create-delete"),
    path("events/<uuid:pk>/", EventDetailView.as_view(), name="events-detail"),
    path("patterns/recompute/", PatternRecomputeView.as_view(), name="patterns-recompute"),
    path("patterns/", PatternListView.as_view(), name="patterns-list"),
    path("patterns/<uuid:pk>/", PatternDetailView.as_view(), name="patterns-detail"),
    path("ask/", AskView.as_view(), name="ask"),
    path("audio/realtime-token/", RealtimeTokenView.as_view(), name="realtime-token"),
    path("audio/transcribe/", AudioBatchTranscribeView.as_view(), name="audio-transcribe"),
    path("analysis/ask/", AnalysisAskView.as_view(), name="analysis-ask"),
    path("analysis/", AnalysisView.as_view(), name="analysis"),
    # Character profiles
    path("profiles/", CharacterProfileListCreateView.as_view(), name="profiles-list-create"),
    path("profiles/<str:uid>/", CharacterProfileDetailView.as_view(), name="profiles-detail"),
    path("profiles/<str:uid>/analyze/", CharacterProfileAnalyzeView.as_view(), name="profiles-analyze"),
    # AI Reflection conversation (Layer 2)
    path("reflection/start/", ReflectionStartView.as_view(), name="reflection-start"),
    path("reflection/next/", ReflectionNextView.as_view(), name="reflection-next"),
    # Screenplay analysis (character dataset pipeline)
    path("screenplay/parse/", ScreenplayParseView.as_view(), name="screenplay-parse"),
    path("screenplay/analyze/", ScreenplayAnalyzeView.as_view(), name="screenplay-analyze"),
    path("screenplay/datasets/", ScreenplayDatasetListView.as_view(), name="screenplay-datasets-list"),
    path("screenplay/datasets/<str:filename>/", ScreenplayDatasetDetailView.as_view(), name="screenplay-datasets-detail"),
    path("screenplay/datasets/<str:filename>/network/", CharacterNetworkBuildView.as_view(), name="screenplay-network-build"),
    # Journey state persistence (shared identity layer)
    path("journey/state/", JourneyStateView.as_view(), name="journey-state"),
    path("journey/responses/", ProvocationResponseView.as_view(), name="journey-responses"),
    path("journey/profile/", JourneyProfileView.as_view(), name="journey-profile"),
    path("journey/profile/values/", ValueProfileView.as_view(), name="journey-profile-values"),
    path("journey/profile/soul/", SoulProfileView.as_view(), name="journey-profile-soul"),
    # V5.0 — Knowledge Graph Platform
    path("import/conversations/", ConversationImportView.as_view(), name="import-conversations"),
    path("graph-tests/", GraphTestsView.as_view(), name="graph-tests"),
    path("graph/query/", GraphQueryView.as_view(), name="graph-query"),
    path("conversation/", LiveConversationView.as_view(), name="live-conversation"),
]
